### ISSUE TITLE
button problem

### ISSUE THREAD

**Issue by nyxriella** [kv4nt/yii2-owl-carousel2#1]
hi kv4nt, thanks for the widget but i got some problem over here. the button navigation only got <span></span> so how i can fix it or edit it with custom button?

**Comment by kv4nt** [comment]
Hi! The widget supports only the owl-carousel options https://owlcarousel2.github.io/OwlCarousel2/docs/api-options.html. Can you explain in more detail which button is in question? Navigation buttons left-right? or navigation circles under the slider?

**Comment by kv4nt** [comment]
Use navText option :
```
navText
Type: Array 
Default: [&#x27;next&#x27;,&#x27;prev&#x27;]

HTML allowed.
```

**Comment by nyxriella** [comment]
ups sorry, i mean the circles nav right under slider. it shown as button but i dont see it anywhere.
![dots](https://user-images.githubusercontent.com/29898864/46772169-d28e7880-cd20-11e8-8b32-7a2f2dc66a5c.png)

already test it with navText but it only affect the navigation.

**Comment by kv4nt** [comment]
Please, add owl-theme class to your container. Like this:
```
....
    kv4nt\owlcarousel\OwlCarouselWidget::begin([
        'container'        => 'div',
        'containerOptions' => [
            'id'    => 'container-id',
            'class' => 'container-class owl-theme'
        ],
....
```

**Comment by kv4nt** [comment]
Hello! Problem is solved?

**Comment by nyxriella** [comment]
oh, it works like a charm. Thank you so much @kv4nt. sorry for being late to reply cuz bussy irl, anyway thanks again!

**Comment by kv4nt** [comment]
You are welcome!
