### ISSUE TITLE
Json::encode versus json_encode

### ISSUE THREAD

**Issue by alexpicolin** [kv4nt/yii2-owl-carousel2#2]
Hi,
first of all, thanks for the Yii2 wrapper class of Owl Carousel v2. That massively helps to quickly implement that nice widget.
I just noticed that using events through `JsExpression()` in the `pluginOptions` break. I found the reason that in `OwlCarouselWidget` class, line 84, you are using `json_encode` instead of `\yii\helps\Json::encode`. The Yii2 version of json-encoding properly interprets `JsExpression` like

`'onInitialize' => new JsExpression("function(){ doSomething(); }")`

to real JavaScript code while `json_encode` just converts the `JsExpression` object into the json string. So, do you mind adding `use yii\helpers\Json;` and changing line 84 to

`$js .= Json::encode($this->pluginOptions) . "\n";` ?

Thanks,
Alexander

**Comment by kv4nt** [comment]
Done. Thank you!
