### ISSUE TITLE
Uncaught TypeError: jQuery(...).owlCarousel is not a function at HTMLDocument

### ISSUE THREAD

**Issue by Roman-Moiseenko** [kv4nt/yii2-owl-carousel2#3]
OwlCarouselWidget::class
`93:         $js = 'JQuery("#' . $this->containerOptions['id'] . '").owlCarousel(' . "\n";`
you need to replace **JQuery** with **$**
Otherwise, sometimes jQuery resets and scripts stop working.

**Comment by kv4nt** [comment]
Ok.

**Comment by kv4nt** [comment]
Done, please use jqueryFunction param

Commit - https://github.com/kv4nt/yii2-owl-carousel2/commit/0cc0ccdd811d3d9b9c6d417daa9272a3b91547cb
