### ISSUE TITLE
Defer or async

### ISSUE THREAD

**Issue by srakl** [kv4nt/yii2-owl-carousel2#4]
Is there away to defer or async the css and js for this? I

**Comment by kv4nt** [comment]
Hello. Can you describe the problem in more detail?

**Comment by srakl** [comment]
> Hello. Can you describe the problem in more detail?

No errors, plugin works great. I was just wondering if there was an option to add `defer` or `async` to the JS and CSS

like this `<script src="blabla.js" defer></script>`

**Comment by kv4nt** [comment]
I will add this feature soon

**Comment by kv4nt** [comment]
@srakl please update composer. in v1.0.5 js loaded defer.
Defer works better then async
